name: Sigstore Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CGO_ENABLED: 0
  PODMAN_VER: v4.2.1

jobs:

  build-fulcio:
    env:
      CGO_ENABLED: 1 # CGO is required for podman
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the remote fulcio repository
        uses: actions/checkout@v2
        with:
          repository: sigstore/fulcio
          ref: main
          path: fulcio
          ref: v1.2.2

      - name: login to registry.redhat.io
        uses: docker/login-action@v1
        with:
          registry: registry.redhat.io
          username: ${{ secrets.RH_REGISTRY_USER }}
          password: ${{ secrets.RH_REGISTRY_PASSWORD }}

      - name: replace the fulcio build image
        run: bash -c -- "sed -i 's#golang:1\.[0-9]*\.[0-9]*@sha256:[a-f0-9]*#registry.redhat.io/rhel9/go-toolset@sha256:113e69fdfa23b41ea82e5da2e4a5b13bca44713fe597ff862ef977a4a2fedda5#g' fulcio/Dockerfile"

      - name: Login to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: build and push fulcio
        run: |
          cd fulcio
          docker build -t quay.io/rcook/fulcio:v1.2.2 .
          docker push quay.io/rcook/fulcio:v1.2.2

  build-rekor:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the remote rekor repository
        uses: actions/checkout@v2
        with:
          repository: sigstore/rekor
          ref: main
          path: rekor
          ref: v1.2.2

      - name: install ko
        uses: imjasonh/setup-ko@v0.6
        env:
          KO_DOCKER_REPO: quay.io/rcook

      - name: login to registry.redhat.io
        uses: docker/login-action@v1
        with:
          registry: registry.redhat.io
          username: ${{ secrets.RH_REGISTRY_USER }}
          password: ${{ secrets.RH_REGISTRY_PASSWORD }}

      - name: Login to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: replace the base image
        run: bash -c -- "sed -i 's#gcr.io/distroless/base:debug-nonroot#registry.access.redhat.com/ubi9/ubi-micro#g' rekor/.ko.yaml"

      - name: build and push rekor
        run: |
          cd rekor
          KO_PREFIX=quay.io/rcook make ko

  build-scaffold:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the remote rekor repository
        uses: actions/checkout@v2
        with:
          repository: sigstore/scaffolding
          ref: main
          path: scaffolding
          ref: v1.2.2

      - name: install ko
        uses: imjasonh/setup-ko@v0.6
        env:
          KO_DOCKER_REPO: quay.io/rcook

      - name: login to registry.redhat.io
        uses: docker/login-action@v1
        with:
          registry: registry.redhat.io
          username: ${{ secrets.RH_REGISTRY_USER }}
          password: ${{ secrets.RH_REGISTRY_PASSWORD }}

      - name: Login to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: replace the base image
        run: |
          bash -c -- "sed -i 's#cgr.dev/chainguard/alpine-base:latest#registry.access.redhat.com/ubi9/ubi-micro#g' scaffolding/.ko.yaml"
          bash -c -- "sed -i 's#gcr.io/cloudsql-docker/gce-proxy:1.33.1-alpine#registry.access.redhat.com/ubi9/ubi-micro#g' scaffolding/.ko.yaml"


      - name: build and push scaffolding
        run: |
          cd scaffolding
          KO_DOCKER_REPO=quay.io/rcook make ko-resolve

  build-trillian:
    # NEED TO SWAP BASE IMAGE!
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the remote rekor repository
        uses: actions/checkout@v2
        with:
          repository: sigstore/rekor
          ref: main
          path: rekor
          ref: v1.2.2

      - name: install ko
        uses: imjasonh/setup-ko@v0.6
        env:
          KO_DOCKER_REPO: quay.io/rcook

      - name: login to registry.redhat.io
        uses: docker/login-action@v1
        with:
          registry: registry.redhat.io
          username: ${{ secrets.RH_REGISTRY_USER }}
          password: ${{ secrets.RH_REGISTRY_PASSWORD }}

      - name: Login to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: build and push trillian
        run: |
          cd rekor
          KO_PREFIX=quay.io/rcook KO_DOCKER_REPO=quay.io/rcook make ko-trillian

  build-tsa:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the remote timestamp-authority repository
        uses: actions/checkout@v2
        with:
          repository: sigstore/timestamp-authority
          ref: main
          path: timestamp-authority
          ref: v1.2.2

      - name: install ko
        uses: imjasonh/setup-ko@v0.6
        env:
          KO_DOCKER_REPO: quay.io/rcook

      - name: login to registry.redhat.io
        uses: docker/login-action@v1
        with:
          registry: registry.redhat.io
          username: ${{ secrets.RH_REGISTRY_USER }}
          password: ${{ secrets.RH_REGISTRY_PASSWORD }}

      - name: Login to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: replace the base image
        run: |
          bash -c -- "sed -i 's#ghcr.io/chainguard-images/static:latest#registry.access.redhat.com/ubi9/ubi-micro#g' timestamp-authority/.ko.yaml"

      - name: build and push tsa
        run: |
          cd timestamp-authority
          KO_PREFIX=quay.io/rcook KO_DOCKER_REPO=quay.io/rcook make ko  
